# Site settings
title: Chong Tang - Computer Science at UVA - University of Virginia
tag_text: Chong Tang
description:

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
