# top level stuff you probably don't need to touch
highlighter: pygments
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://blog.ctang.me
baseurl: /
title: Chong Tang
author: Chong Tang
description: Personal homepage and blog
avatar: profile.png
email: ctang@virginia.edu
github: chongtang # username
twitter: chongtanguva
linkedin: chongtang
stackoverflow: users/1895314/chong-tang #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: 
google_analytics: 


# needed for travis-ci build
exclude: [vendor]
